name: Facebook Auto Like

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'  # Chạy mỗi ngày lúc 8h sáng VN (1h UTC)

jobs:
  like_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run script
        env:
          FB_EMAIL: ${{ secrets.FB_EMAIL }}
          FB_PASS: ${{ secrets.FB_PASS }}
        run: node index.js
